name: Node Continuous Integration

on:
  push:
    branches: [ develop ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci 
      - run: git config --global user.email "action@github.com"
      - run: git config --global user.name "Github Action"
      - run: npm run deploy 